"""
check_lambda_vs_ou.py
─────────────────────
Compares Dixon-Coles model lambda predictions to bookmaker
over/under total goals lines for WC 2026 group stage matches.

The O/U line IS the bookmaker's implied total goals expectation,
which is the same quantity as lambda_home + lambda_away.

Comparing the two tells you:
  - Whether the model is over- or under-predicting goals vs the market
  - The implied k adjustment (ou_avg / lambda_avg)
  - Which specific matches diverge most (where k matters most)

Requires:
    data/wc2026_lambda_check.csv  — already generated by check_lambda_2026.py
    data/wc2026_ou_lines.csv      — you create this (see format below)

Format for wc2026_ou_lines.csv:
    home_team, away_team, ou_line
    Brazil, Haiti, 4.50
    Germany, Curaçao, 4.00
    ...

    ou_line is the main total goals line from your bookmaker.
    Use the midpoint if the line is listed as e.g. 2.75 (over/under 2.75).
    Pinnacle is the best source — sharpest lines, lowest margin.
    You don't need all 72 — even 30-40 of the close matches is enough.
    Skip the extreme mismatches (lambda > 4.0) — k won't change those
    predictions regardless of value.

Usage:
    py -3 check_lambda_vs_ou.py
"""

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
from pathlib import Path
from src.odds_loader import _resolve_team

PROJECT_ROOT  = Path(__file__).resolve().parent
LAMBDA_PATH   = PROJECT_ROOT / "data" / "wc2026_lambda_check.csv"
OU_PATH       = PROJECT_ROOT / "data" / "wc2026_ou_lines.csv"

# From the k analysis:
LAMBDA_RECENT_WC_AVG = 2.6875  # actual avg goals in 2022 (our target)

# ─────────────────────────────────────────────────────────────
# 1. Load model lambdas
# ─────────────────────────────────────────────────────────────
lambdas = pd.read_csv(LAMBDA_PATH).dropna(subset=["lambda_total"])
lambdas["home_team"] = lambdas["home_team"].astype(str).str.strip().apply(_resolve_team)
lambdas["away_team"] = lambdas["away_team"].astype(str).str.strip().apply(_resolve_team)
lambdas["match_key"] = lambdas["home_team"] + " vs " + lambdas["away_team"]

print(f"Model lambdas loaded  : {len(lambdas)} matches")
print(f"Model avg lambda      : {lambdas['lambda_total'].mean():.4f}")

# ─────────────────────────────────────────────────────────────
# 2. Load O/U lines
# ─────────────────────────────────────────────────────────────
if not OU_PATH.exists():
    raise FileNotFoundError(
        f"\nFile not found: {OU_PATH}\n\n"
        "Create a CSV with columns: home_team, away_team, ou_line\n"
        "One row per match. You don't need all 72 —\n"
        "focus on matches with lambda_total between 2.0 and 3.5\n"
        "(the range where k actually changes predictions).\n"
    )

ou = pd.read_csv(OU_PATH)
ou["home_team"] = ou["home_team"].astype(str).str.strip().apply(_resolve_team)
ou["away_team"] = ou["away_team"].astype(str).str.strip().apply(_resolve_team)
ou["ou_line"]   = ou["ou_line"].astype(float)

print(f"O/U lines loaded      : {len(ou)} matches")
print(f"O/U avg               : {ou['ou_line'].mean():.4f}")

# ─────────────────────────────────────────────────────────────
# 3. Merge on both orientations (home/away might be reversed)
# ─────────────────────────────────────────────────────────────
merged = lambdas.merge(
    ou,
    on=["home_team", "away_team"],
    how="inner",
)

# Also try reversed orientation
ou_rev = ou.rename(columns={"home_team": "away_team", "away_team": "home_team"})
merged_rev = lambdas.merge(
    ou_rev,
    on=["home_team", "away_team"],
    how="inner",
)
# Combine, deduplicate
merged = pd.concat([merged, merged_rev]).drop_duplicates(subset=["home_team", "away_team"])

if len(merged) == 0:
    print(
        "\nERROR: No matches could be merged. Check that team names\n"
        "in your O/U CSV match the FIFA names in the lambda file.\n"
        "Run this to see the lambda file team names:\n"
        "  import pandas as pd\n"
        "  df = pd.read_csv('data/wc2026_lambda_check.csv')\n"
        "  print(df[['home_team','away_team']].to_string())\n"
    )
    exit(1)

print(f"Matched               : {len(merged)} / {len(ou)} O/U lines")
if len(merged) < len(ou):
    unmatched = set(
        ou["home_team"] + " vs " + ou["away_team"]
    ) - set(
        merged["home_team"] + " vs " + merged["away_team"]
    )
    print(f"Unmatched lines (check names):")
    for m in sorted(unmatched):
        print(f"  {m}")

# ─────────────────────────────────────────────────────────────
# 4. Compute per-match ratio and implied k
# ─────────────────────────────────────────────────────────────
merged["ratio"]      = merged["ou_line"] / merged["lambda_total"]
merged["delta"]      = merged["ou_line"] - merged["lambda_total"]
merged["match_key"]  = merged["home_team"] + " vs " + merged["away_team"]

avg_lambda_matched = merged["lambda_total"].mean()
avg_ou             = merged["ou_line"].mean()
implied_k          = avg_ou / avg_lambda_matched

# ─────────────────────────────────────────────────────────────
# 5. Print full comparison table
# ─────────────────────────────────────────────────────────────
print(f"\n{'=' * 68}")
print("MATCH-BY-MATCH: MODEL LAMBDA vs BOOKMAKER O/U LINE")
print(f"{'=' * 68}")
print(f"\n  {'Match':<40}  {'λ model':>8}  {'O/U line':>8}  {'Δ':>6}  {'ratio':>6}")
print(f"  {'─' * 40}  {'─' * 8}  {'─' * 8}  {'─' * 6}  {'─' * 6}")

for _, row in merged.sort_values("lambda_total", ascending=False).iterrows():
    delta = row["ou_line"] - row["lambda_total"]
    flag  = "  ◄" if abs(delta) > 0.5 else ""
    print(
        f"  {row['match_key']:<40}  "
        f"{row['lambda_total']:>8.3f}  "
        f"{row['ou_line']:>8.3f}  "
        f"{delta:>+6.3f}  "
        f"{row['ratio']:>6.3f}"
        f"{flag}"
    )

# ─────────────────────────────────────────────────────────────
# 6. Summary
# ─────────────────────────────────────────────────────────────
print(f"\n{'=' * 68}")
print("SUMMARY")
print(f"{'=' * 68}")
print(f"\n  Matches in comparison      : {len(merged)}")
print(f"  Model avg λ (matched set)  : {avg_lambda_matched:.4f}")
print(f"  Bookmaker avg O/U          : {avg_ou:.4f}")
print(f"  Implied k                  : {implied_k:.3f}  (= {avg_ou:.4f} / {avg_lambda_matched:.4f})")
print(f"  Model vs book bias         : {avg_lambda_matched - avg_ou:+.4f}  "
      f"({'model over-predicts goals' if avg_lambda_matched > avg_ou else 'model under-predicts goals'})")

# Segment by lambda range — k matters most in the middle range
print(f"\n  By lambda range (k matters most in 2.0–3.5 range):")
print(f"\n  {'Range':<15}  {'N':>4}  {'Avg λ':>7}  {'Avg O/U':>8}  {'Implied k':>10}")
print(f"  {'─' * 15}  {'─' * 4}  {'─' * 7}  {'─' * 8}  {'─' * 10}")

for lo, hi in [(0.0, 2.5), (2.5, 3.0), (3.0, 3.5), (3.5, 99.0)]:
    seg = merged[(merged["lambda_total"] >= lo) & (merged["lambda_total"] < hi)]
    if len(seg) == 0:
        continue
    label = f"{lo:.1f}–{hi:.1f}" if hi < 99 else f"{lo:.1f}+"
    k_seg = seg["ou_line"].mean() / seg["lambda_total"].mean()
    print(
        f"  {label:<15}  {len(seg):>4}  "
        f"{seg['lambda_total'].mean():>7.3f}  "
        f"{seg['ou_line'].mean():>8.3f}  "
        f"{k_seg:>10.3f}"
    )

# ─────────────────────────────────────────────────────────────
# 7. Decision
# ─────────────────────────────────────────────────────────────
print(f"\n{'=' * 68}")
print("DECISION")
print(f"{'=' * 68}")

if implied_k >= 0.98:
    verdict = (
        f"  Implied k = {implied_k:.3f} — effectively 1.0.\n"
        f"  Model and market agree on total goals.\n"
        f"  Use k=1.00. The 48-team expansion has already inflated\n"
        f"  the model's lambdas to match real-world expectations.\n"
        f"  Do NOT apply k=1.15 — it would significantly over-predict\n"
        f"  goals and push predictions toward high-scoring scorelines."
    )
elif implied_k >= 0.92:
    verdict = (
        f"  Implied k = {implied_k:.3f} — mild model over-prediction.\n"
        f"  Consider k={implied_k:.2f} rounded to nearest 0.05.\n"
        f"  The model slightly over-predicts goals vs the market.\n"
        f"  A small downward adjustment is warranted."
    )
else:
    verdict = (
        f"  Implied k = {implied_k:.3f} — significant model over-prediction.\n"
        f"  Model is substantially above the market on total goals.\n"
        f"  Focus on the 2.0–3.5 lambda range (close matches) —\n"
        f"  check if the implied k is consistent in that range.\n"
        f"  If yes, use k={round(implied_k * 20) / 20:.2f}."
    )

print(f"\n{verdict}\n")

print(
    f"  NOTE: Whatever k you settle on, the critical check is the\n"
    f"  2.5–3.5 lambda bucket — that is where predictions sit near\n"
    f"  scoring boundaries and k actually changes the scoreline.\n"
    f"  The extreme mismatch games (λ > 4.0) will predict correctly\n"
    f"  regardless of k value."
)