services:
  predictor-ui:
    build: .
    container_name: world-cup-ui
    restart: unless-stopped
    volumes:
      - ./predictions_history.csv:/app/predictions_history.csv
    expose:
      - "8501"
    networks:
      - proxy
    deploy:
      resources:
        limits:
          memory: 150M

networks:
  proxy:
    external: true