# src/mappings.py

# FIFA 3-letter code → full name as it appears in the Kaggle results.csv dataset
# Covers all teams that appeared in World Cups 2002-2022

FIFA_CODE_TO_NAME = {
    'ALG': 'Algeria',
    'ANG': 'Angola',
    'ARG': 'Argentina',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'BEL': 'Belgium',
    'BIH': 'Bosnia and Herzegovina',
    'BRA': 'Brazil',
    'CAN': 'Canada',
    'CHI': 'Chile',
    'CHN': 'China PR',
    'CIV': 'Ivory Coast',
    'CMR': 'Cameroon',
    'COL': 'Colombia',
    'COD': 'DR Congo',
    'CRC': 'Costa Rica',
    'CRO': 'Croatia',
    'CUW': 'Curaçao',
    'CPV': 'Cape Verde',
    'CZE': 'Czech Republic',
    'DEN': 'Denmark',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'ENG': 'England',
    'ESP': 'Spain',
    'FRA': 'France',
    'GER': 'Germany',
    'GHA': 'Ghana',
    'GRE': 'Greece',
    'HON': 'Honduras',
    'HAI': 'Haiti',
    'IRL': 'Republic of Ireland',
    'IRN': 'Iran',
    'IRQ': 'Iraq',
    'ISL': 'Iceland',
    'ITA': 'Italy',
    'JPN': 'Japan',
    'JOR': 'Jordan',
    'KOR': 'South Korea',
    'KSA': 'Saudi Arabia',
    'MAR': 'Morocco',
    'MEX': 'Mexico',
    'NED': 'Netherlands',
    'NGA': 'Nigeria',
    'NOR': 'Norway',
    'NZL': 'New Zealand',
    'PAN': 'Panama',
    'PAR': 'Paraguay',
    'PER': 'Peru',
    'POL': 'Poland',
    'POR': 'Portugal',
    'PRK': 'North Korea',
    'QAT': 'Qatar',
    'RSA': 'South Africa',
    'RUS': 'Russia',
    'SCO': 'Scotland',
    'SEN': 'Senegal',
    'SRB': 'Serbia',
    'SUI': 'Switzerland',
    'SVK': 'Slovakia',
    'SVN': 'Slovenia',
    'SWE': 'Sweden',
    'TOG': 'Togo',
    'TRI': 'Trinidad and Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Turkey',
    'UKR': 'Ukraine',
    'URU': 'Uruguay',
    'USA': 'United States',
    'UZB': 'Uzbekistan',
    'WAL': 'Wales',
}

def code_to_name(code):
    """
    Translates a FIFA 3-letter code to the full name used in the Kaggle dataset.
    Raises a clear error if the code is missing, so bugs surface immediately
    rather than silently producing wrong results.
    """
    if code not in FIFA_CODE_TO_NAME:
        raise KeyError(f"FIFA code '{code}' not found in mappings. Add it to mappings.py.")
    return FIFA_CODE_TO_NAME[code]

FIFA_NAME_TO_CONFEDERATION = {
    'Afghanistan': 'AFC',
    'Albania': 'UEFA',
    'Algeria': 'CAF',
    'American Samoa': 'OFC',
    'Andalusia': 'UEFA',
    'Andorra': 'UEFA',
    'Angola': 'CAF',
    'Antigua and Barbuda': 'CONCACAF',
    'Argentina': 'CONMEBOL',
    'Armenia': 'UEFA',
    'Aruba': 'CONCACAF',
    'Australia': 'AFC',
    'Austria': 'UEFA',
    'Azerbaijan': 'UEFA',
    'Bahrain': 'AFC',
    'Bangladesh': 'AFC',
    'Barbados': 'CONCACAF',
    'Basque Country': 'UEFA',
    'Belarus': 'UEFA',
    'Belgium': 'UEFA',
    'Belize': 'CONCACAF',
    'Benin': 'CAF',
    'Bermuda': 'CONCACAF',
    'Bhutan': 'AFC',
    'Bolivia': 'CONMEBOL',
    'Bosnia and Herzegovina': 'UEFA',
    'Botswana': 'CAF',
    'Brazil': 'CONMEBOL',
    'Brittany': 'UEFA',
    'Brunei': 'AFC',
    'Bulgaria': 'UEFA',
    'Burkina Faso': 'CAF',
    'Burundi': 'CAF',
    'Cambodia': 'AFC',
    'Cameroon': 'CAF',
    'Canada': 'CONCACAF',
    'Cape Verde': 'CAF',
    'Catalonia': 'UEFA',
    'Cayman Islands': 'CONCACAF',
    'Central African Republic': 'CAF',
    'Chad': 'CAF',
    'Chile': 'CONMEBOL',
    'China PR': 'AFC',
    'Colombia': 'CONMEBOL',
    'Comoros': 'CAF',
    'Congo': 'CAF',
    'Cook Islands': 'OFC',
    'Corsica': 'UEFA',
    'Costa Rica': 'CONCACAF',
    'Croatia': 'UEFA',
    'Cuba': 'CONCACAF',
    'Curaçao': 'CONCACAF',
    'Cyprus': 'UEFA',
    'Czech Republic': 'UEFA',
    'Czechoslovakia': 'UEFA',
    'DR Congo': 'CAF',
    'Denmark': 'UEFA',
    'Djibouti': 'CAF',
    'Dominica': 'CONCACAF',
    'Dominican Republic': 'CONCACAF',
    'Ecuador': 'CONMEBOL',
    'Egypt': 'CAF',
    'El Salvador': 'CONCACAF',
    'England': 'UEFA',
    'Equatorial Guinea': 'CAF',
    'Eritrea': 'CAF',
    'Estonia': 'UEFA',
    'Eswatini': 'CAF',
    'Ethiopia': 'CAF',
    'Faroe Islands': 'UEFA',
    'Fiji': 'OFC',
    'Finland': 'UEFA',
    'France': 'UEFA',
    'French Guiana': 'CONCACAF',
    'Gabon': 'CAF',
    'Galicia': 'UEFA',
    'Gambia': 'CAF',
    'Georgia': 'UEFA',
    'German DR': 'UEFA',
    'Germany': 'UEFA',
    'Ghana': 'CAF',
    'Gibraltar': 'UEFA',
    'Greece': 'UEFA',
    'Grenada': 'CONCACAF',
    'Guadeloupe': 'CONCACAF',
    'Guam': 'AFC',
    'Guatemala': 'CONCACAF',
    'Guinea': 'CAF',
    'Guinea-Bissau': 'CAF',
    'Guyana': 'CONCACAF',
    'Haiti': 'CONCACAF',
    'Honduras': 'CONCACAF',
    'Hong Kong': 'AFC',
    'Hungary': 'UEFA',
    'Iceland': 'UEFA',
    'India': 'AFC',
    'Indonesia': 'AFC',
    'Iran': 'AFC',
    'Iraq': 'AFC',
    'Israel': 'UEFA',
    'Italy': 'UEFA',
    'Ivory Coast': 'CAF',
    'Jamaica': 'CONCACAF',
    'Japan': 'AFC',
    'Jordan': 'AFC',
    'Kazakhstan': 'UEFA',
    'Kenya': 'CAF',
    'Kosovo': 'UEFA',
    'Kuwait': 'AFC',
    'Kyrgyzstan': 'AFC',
    'Laos': 'AFC',
    'Latvia': 'UEFA',
    'Lebanon': 'AFC',
    'Lesotho': 'CAF',
    'Liberia': 'CAF',
    'Libya': 'CAF',
    'Liechtenstein': 'UEFA',
    'Lithuania': 'UEFA',
    'Luxembourg': 'UEFA',
    'Macau': 'AFC',
    'Madagascar': 'CAF',
    'Malawi': 'CAF',
    'Malaysia': 'AFC',
    'Maldives': 'AFC',
    'Mali': 'CAF',
    'Malta': 'UEFA',
    'Martinique': 'CONCACAF',
    'Mauritania': 'CAF',
    'Mauritius': 'CAF',
    'Mexico': 'CONCACAF',
    'Moldova': 'UEFA',
    'Mongolia': 'AFC',
    'Montenegro': 'UEFA',
    'Morocco': 'CAF',
    'Mozambique': 'CAF',
    'Myanmar': 'AFC',
    'Namibia': 'CAF',
    'Nepal': 'AFC',
    'Netherlands': 'UEFA',
    'New Zealand': 'OFC',
    'Nicaragua': 'CONCACAF',
    'Niger': 'CAF',
    'Nigeria': 'CAF',
    'North Korea': 'AFC',
    'North Macedonia': 'UEFA',
    'Northern Ireland': 'UEFA',
    'Norway': 'UEFA',
    'Oman': 'AFC',
    'Pakistan': 'AFC',
    'Palestine': 'AFC',
    'Panama': 'CONCACAF',
    'Papua New Guinea': 'OFC',
    'Paraguay': 'CONMEBOL',
    'Peru': 'CONMEBOL',
    'Philippines': 'AFC',
    'Poland': 'UEFA',
    'Portugal': 'UEFA',
    'Puerto Rico': 'CONCACAF',
    'Qatar': 'AFC',
    'Republic of Ireland': 'UEFA',
    'Romania': 'UEFA',
    'Russia': 'UEFA',
    'Rwanda': 'CAF',
    'Saint Kitts and Nevis': 'CONCACAF',
    'Saint Lucia': 'CONCACAF',
    'Saint Vincent and the Grenadines': 'CONCACAF',
    'Samoa': 'OFC',
    'San Marino': 'UEFA',
    'Saudi Arabia': 'AFC',
    'Scotland': 'UEFA',
    'Senegal': 'CAF',
    'Serbia': 'UEFA',
    'Seychelles': 'CAF',
    'Sierra Leone': 'CAF',
    'Silesia': 'UEFA',
    'Singapore': 'AFC',
    'Slovakia': 'UEFA',
    'Slovenia': 'UEFA',
    'Solomon Islands': 'OFC',
    'Somalia': 'CAF',
    'South Africa': 'CAF',
    'South Korea': 'AFC',
    'South Sudan': 'CAF',
    'Spain': 'UEFA',
    'Sri Lanka': 'AFC',
    'Sudan': 'CAF',
    'Suriname': 'CONCACAF',
    'Sweden': 'UEFA',
    'Switzerland': 'UEFA',
    'Syria': 'AFC',
    'São Tomé and Príncipe': 'CAF',
    'Tahiti': 'OFC',
    'Taiwan': 'AFC',
    'Tajikistan': 'AFC',
    'Tanzania': 'CAF',
    'Thailand': 'AFC',
    'Timor-Leste': 'AFC',
    'Togo': 'CAF',
    'Tonga': 'OFC',
    'Trinidad and Tobago': 'CONCACAF',
    'Tunisia': 'CAF',
    'Turkey': 'UEFA',
    'Turkmenistan': 'AFC',
    'Uganda': 'CAF',
    'Ukraine': 'UEFA',
    'United Arab Emirates': 'AFC',
    'United States': 'CONCACAF',
    'Uruguay': 'CONMEBOL',
    'Uzbekistan': 'AFC',
    'Vanuatu': 'OFC',
    'Venezuela': 'CONMEBOL',
    'Vietnam': 'AFC',
    'Wales': 'UEFA',
    'Yemen': 'AFC',
    'Yugoslavia': 'UEFA',
    'Zambia': 'CAF',
    'Zimbabwe': 'CAF',
}

def name_to_confederation(name):
    """
    Translates a FIFA team name to the confederation used in the Dixon-Coles fitting.
    """
    if name not in FIFA_NAME_TO_CONFEDERATION:
        raise KeyError(f"Team name '{name}' not found in mappings. Add it to mappings.py.")
    return FIFA_NAME_TO_CONFEDERATION[name]

ODDS_NAME_TO_FIFA = {
    'USA':                  'United States',
    'Bosnia & Herzegovina': 'Bosnia and Herzegovina',
    'Bosnia-Herzegovina':   'Bosnia and Herzegovina',

    # 2006 / 2010 Spanish names
    'Alemania':             'Germany',
    'Angola':               'Angola',
    'Arabia Saudí':         'Saudi Arabia',
    'Argelia':              'Algeria',
    'Argentina':            'Argentina',
    'Australia':            'Australia',
    'Brasil':               'Brazil',
    'Camerún':              'Cameroon',
    'Chile':                'Chile',
    'Corea del Norte':      'North Korea',
    'Corea del Sur':        'South Korea',
    'Costa Rica':           'Costa Rica',
    'Costa de Marfil':      'Ivory Coast',
    'Croacia':              'Croatia',
    'Dinamarca':            'Denmark',
    'EE. UU.':              'United States',
    'Ecuador':              'Ecuador',
    'Eslovaquia':           'Slovakia',
    'Eslovenia':            'Slovenia',
    'España':               'Spain',
    'Francia':              'France',
    'Ghana':                'Ghana',
    'Grecia':               'Greece',
    'Honduras':             'Honduras',
    'Inglaterra':           'England',
    'Irán':                 'Iran',
    'Italia':               'Italy',
    'Japón':                'Japan',
    'México':               'Mexico',
    'Nigeria':              'Nigeria',
    'Nueva Zelanda':        'New Zealand',
    'Paraguay':             'Paraguay',
    'Países Bajos':         'Netherlands',
    'Polonia':              'Poland',
    'Portugal':             'Portugal',
    'República Checa':      'Czech Republic',
    'Serbia':               'Serbia',
    'Serbia and Montenegro':'Serbia',
    'Sudáfrica':            'South Africa',
    'Suecia':               'Sweden',
    'Suiza':                'Switzerland',
    'Togo':                 'Togo',
    'Trinidad y Tobago':    'Trinidad and Tobago',
    'Túnez':                'Tunisia',
    'Ucrania':              'Ukraine',
    'Uruguay':              'Uruguay',
}

SPANISH_NAME_TO_FIFA = {
    "Alemania": "Germany",
    "Arabia Saudí": "Saudi Arabia",
    "Argelia": "Algeria",
    "Austria": "Austria",
    "Bermudas": "Bermuda",
    "Benín": "Benin",
    "Bolivia": "Bolivia",
    "Botsuana": "Botswana",
    "Brasil": "Brazil",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Bélgica": "Belgium",
    "Cabo Verde": "Cape Verde",
    "Camerún": "Cameroon",
    "Canadá": "Canada",
    "Catar": "Qatar",
    "Chile": "Chile",
    "Colombia": "Colombia",
    "Comores": "Comoros",
    "Costa de Marfil": "Ivory Coast",
    "Croacia": "Croatia",
    "Curazao": "Curaçao",
    "Dinamarca": "Denmark",
    "EE. UU.": "United States",
    "Ecuador": "Ecuador",
    "Egipto": "Egypt",
    "El Salvador": "El Salvador",
    "Escocia": "Scotland",
    "Eslovaquia": "Slovakia",
    "Eslovenia": "Slovenia",
    "España": "Spain",
    "Etiopía": "Ethiopia",
    "Finlandia": "Finland",
    "Francia": "France",
    "Gabón": "Gabon",
    "Gales": "Wales",
    "Georgia": "Georgia",
    "Ghana": "Ghana",
    "Granada": "Grenada",
    "Guadalupe": "Guadeloupe",
    "Guatemala": "Guatemala",
    "Guayana Francesa": "French Guiana",
    "Guinea": "Guinea",
    "Guinea Ecuatorial": "Equatorial Guinea",
    "Guinea-Bisáu": "Guinea-Bissau",
    "Guyana": "Guyana",
    "Haití": "Haiti",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Hungría": "Hungary",
    "Inglaterra": "England",
    "Irlanda": "Republic of Ireland",
    "Irlanda del Norte": "Northern Ireland",
    "Islandia": "Iceland",
    "Irán": "Iran",
    "Italia": "Italy",
    "Jamaica": "Jamaica",
    "Japón": "Japan",
    "Kenia": "Kenya",
    "Macedonia del Norte": "North Macedonia",
    "Madagascar": "Madagascar",
    "Malaui": "Malawi",
    "Mali": "Mali",
    "Marruecos": "Morocco",
    "Martinica": "Martinique",
    "Mauritania": "Mauritania",
    "Mozambique": "Mozambique",
    "México": "Mexico",
    "Namibia": "Namibia",
    "Nicaragua": "Nicaragua",
    "Nigeria": "Nigeria",
    "Panamá": "Panama",
    "Paraguay": "Paraguay",
    "Países Bajos": "Netherlands",
    "Perú": "Peru",
    "Polonia": "Poland",
    "Portugal": "Portugal",
    "RD Congo": "DR Congo",
    "República Checa": "Czech Republic",
    "República Dominicana": "Dominican Republic",
    "Rumanía": "Romania",
    "Rusia": "Russia",
    "Saint Kitts y Nevis": "Saint Kitts and Nevis",
    "Senegal": "Senegal",
    "Sierra Leona": "Sierra Leone",
    "Sudáfrica": "South Africa",
    "Sudán": "Sudan",
    "Suecia": "Sweden",
    "Suiza": "Switzerland",
    "Surinam": "Suriname",
    "Tanzania": "Tanzania",
    "Turquía": "Turkey",
    "Túnez": "Tunisia",
    "Ucrania": "Ukraine",
    "Uganda": "Uganda",
    "Uruguay": "Uruguay",
    "Venezuela": "Venezuela",
    "Zambia": "Zambia",
    "Zimbabue": "Zimbabwe",
}

ODDS_NAME_TO_FIFA.update(
    SPANISH_NAME_TO_FIFA
)